schema_version = 3

[project]
uuid = "f67ba78d-5e18-4cfb-a4fb-73b9f31e2cfb"
name = "speechscope"

[ledgers.taskledger.mounts.data]
storage = "external"
root = "../ledger"

[ledgers.taskledger.mounts.runtime]
storage = "user-data"

[ledgers.taskledger.mounts.logs]
storage = "user-data"

[ledgers.taskledger.mounts.indexes]
storage = "cache"

[ledgers.releaseledger.mounts.data]
storage = "project"

[ledgers.releaseledger.mounts.indexes]
storage = "cache"
